apiVersion: v1
kind: Service
metadata:
  name: ai-model-service
  namespace: ai-model-service
  labels:
    app: ai-model-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ai-model-service
